---
title: "4_wind_data.rmd"
author: "iganelin"
date: "November 13, 2017"
output: html_document
---

### Loading libraries
```{r message=FALSE}
library(tidyverse)
library(knitr)
library(magrittr)
library(dplyr)
library(readr)
library(stringr)
library(ggplot2)
library(ggfortify)
```

```{r}
read_wind_data <- function(gtm.rawData, save_flag){
  #Reads the wind turbine data CSV, cleans and prints it out.
  #gtm.rawData <- read.csv(input, header = TRUE)
  gtm.dat <- within(gtm.rawData, rm("X.GV.SD_04","X.GV.SD_05","X.GV.SD_38", "X.GV.HRR_GeneratorWindingTemp.1"))
  c_names <- colnames(gtm.dat, do.NULL = TRUE, prefix = "col")
  raw_data <- str_replace(c_names, "X.GV.", "")
  names(gtm.dat) <- raw_data

  return(gtm.dat)
}
```

```{r}
mkdirs <- function(fp) {
    if(!file.exists(fp)) {
        mkdirs(dirname(source_local(), fp))
        dir.create(fp)
    }
} 
```

Function plots var1 against var2 from data-frame df and saves if save_flag == TRUE:
```{r}
plot_and_save <- function(df, var1, var2, save_flag){
    my_plot <- ggplot(df, aes(df[[var1]], df[[var2]])) +
      geom_point() +
      geom_smooth(se=FALSE)
  
    if(save_flag == TRUE){
    #mkdirs(media)
      ggsave("media/my_plot.png", plot = my_plot)
    }
}
```

PCA plus Linear regression
```{r}
le_lin_fit <- function(vars, gentemp, save_flag=TRUE) {
  PCA <- prcomp(vars, center = TRUE, scale. = TRUE) 
  print(PCA$rotation)
  summary(PCA)
  the_fit <- lm(gentemp ~ vars$HRR_kVAR + vars$HRR_WTCorrectedWindSpeed)
  #OR
  #mutate(the_fit = map(data, ~ lm(gtm.gentemp ~ PCA$rotation, data = .x)))
  coef(the_fit)
  if(save_flag == TRUE){
   	my_plot <- plot(PCA, type = "l")
    ggsave("media/my_pca_plot.png", plot = my_plot)
  	}
  }
```

Let's plot a few graphs and complete PCA analysis for generator temperature using the rest of the variables.

```{r}
input_csv <- read.csv(file="clean_wind_data.csv", header=TRUE, sep=",")
plot_and_save(input_csv, "HRR_WTCorrectedWindSpeed", "HRR_kW", TRUE)

gtm.dat <- input_csv

end = ncol(input_csv)
gtm.gentemp <- gtm.dat[,end]
gtm.vars <- gtm.dat[,4:end-1]

le_lin_fit(gtm.vars, gtm.gentemp, save_flag=TRUE)

plot_and_save(gtm.dat, "HRR_WTCorrectedWindSpeed", "HRR_kW", TRUE)

gtm.pca <- prcomp(gtm.vars, center = TRUE, scale. = TRUE) 
head(gtm.pca$rotation)

plot_pca <- plot(gtm.pca, type = "l")
ggsave("media/plot_pca.png", plot = plot_pca)
summary(head(gtm.pca))
```


